name: pull-request-lint

on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: yarn
      - name: Lint flow
        run: yarn flow
      - name: Lint Eslint
        run: npx eslint . --ignore-path .gitignore --ignore-path .eslintignore
